services:
  db:
    image: postgres:18
    container_name: order_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.6.1
    container_name: order_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: order_fastapi_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: sh -c "uv run --active alembic upgrade head && uv run --active main.py"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_TTL=300.0


volumes:
  postgres_data:
